import Head from "next/head";
import { RandomFox } from "@/components/random_fox"

export default function Home() {
  return (

    <div>
      <Head>
        <title>RandomFox</title>
        <meta name="description" content="generated by randomFox"/>
        <link rel="icon" href="../public/favicon.ico"/>
      </Head>
      <main>
        <h1 className="text-3xl font-bold underline">
          Hello world!
        </h1>
        <RandomFox/>
      </main>

      <footer>

      </footer>
    </div>
  )
}
